let links = document
    .querySelectorAll(".container .links .link");
let divs = document
    .querySelectorAll(".container-content div");

links.forEach((link) => {
    link.addEventListener('click', removeActiveClass);
    link.addEventListener('click', attachDiv);
});

function removeActiveClass() {
    links.forEach((link) => {
        link.classList.remove("active");
    });
    this.classList.add("active");
}

function attachDiv() {
    divs.forEach((div) => {
        div.style.display = "none";
    });
    document
        .querySelectorAll(this.dataset.appear)
            .forEach((el) => {
        el.style.display = "flex";
    });
}

// function grid(n) {
//     let alphabetLetter = "";
//     let test = [];
//     let rows = [];
//     for (let i = 0; i < 26; i += 1) {
//         let letter = String.fromCharCode(97 + i);
//         alphabetLetter += letter;
//     }
//     for (let j = 0; j < n; j += 1) {
//         for (let i = 0; i < n; i += 1) {
//             rows.push(alphabetLetter[i]);
//         }
//     }
//     return rows;
// }
// console.log(grid(4));

// const products = [
//     {
//         title: "Dinosaur T-shirt 01",
//         price: "189000",
//         categorySlug: "t-shirt",
//         colors: ["white", "red", "orange"],
//         slug: "t-shirt-dinosaur-01",
//         size: ["s", "m", "l", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Dinosaur T-shirt 02",
//         price: "159000",
//         categorySlug: "t-shirt",
//         colors: ["white", "red", "blue"],
//         slug: "t-shirt-dinosaur-02",
//         size: ["s", "m"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Dinosaur T-shirt 03",
//         price: "190000",
//         categorySlug: "t-shirt",
//         colors: ["white", "red", "orange", "yellow"],
//         slug: "t-shirt-dinosaur-03",
//         size: ["m"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Polo T-shirt 04",
//         price: "194000",
//         categorySlug: "t-shirt",
//         colors: ["white", "orange", "blue"],
//         slug: "t-shirt-polo-04",
//         size: ["xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Polo T-shirt 05",
//         price: "194000",
//         categorySlug: "t-shirt",
//         colors: ["white", "pink"],
//         slug: "t-shirt-polo-05",
//         size: ["xxl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Polo T-shirt 06",
//         price: "194000",
//         categorySlug: "t-shirt",
//         colors: ["black"],
//         slug: "t-shirt-polo-06",
//         size: ["s", "m", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Checkered somi shirt 07",
//         price: "194000",
//         categorySlug: "shirt",
//         colors: ["white", "red", "orange", "blue"],
//         slug: "shirt-caro-07",
//         size: ["l", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Long sleeve somi 08",
//         price: "194000",
//         categorySlug: "shirt",
//         colors: ["white", "red", "black"],
//         slug: "shirt-dai-tay-08",
//         size: ["s", "m", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Long sleeve somi 09",
//         price: "194000",
//         categorySlug: "shirt",
//         colors: ["white", "blue"],
//         slug: "shirt-tay-dai-09",
//         size: ["m"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Stylish jeans 10",
//         price: "194000",
//         categorySlug: "jeans",
//         colors: ["blue", "black"],
//         slug: "jeans-phong-cach-10",
//         size: ["l"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Jeans11",
//         price: "194000",
//         categorySlug: "jeans",
//         colors: ["blue", "black"],
//         slug: "jeans-11",
//         size: ["s", "m", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Jeans12",
//         price: "194000",
//         categorySlug: "jeans",
//         colors: ["blue"],
//         slug: "jeans-12",
//         size: ["s", "m", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Dinosaur T-shirt 13",
//         price: "189000",
//         categorySlug: "t-shirt",
//         colors: ["white", "red"],
//         slug: "t-shirt-dinosaur-13",
//         size: ["s", "m", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Dinosaur T-shirt 14",
//         price: "159000",
//         categorySlug: "t-shirt",
//         colors: ["white", "blue"],
//         slug: "t-shirt-dinosaur-14",
//         size: ["s", "m"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Dinosaur T-shirt 15",
//         price: "190000",
//         categorySlug: "t-shirt",
//         colors: ["red", "blue"],
//         slug: "t-shirt-dinosaur-15",
//         size: ["xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Long sleeve somi 16",
//         price: "194000",
//         categorySlug: "shirt",
//         colors: ["blue", "black"],
//         slug: "shirt-dai-tay-16",
//         size: ["m", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "long sleeve shirt 17",
//         price: "194000",
//         categorySlug: "shirt",
//         colors: ["white", "blue"],
//         slug: "shirt-tay-dai-17",
//         size: ["s", "l", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     {
//         title: "Stylish jeans18",
//         price: "194000",
//         categorySlug: "jeans",
//         colors: ["blue", "black"],
//         slug: "jeans-phong-cach-18",
//         size: ["s", "m", "l", "xl"],
//         description: "The presence of basic round-neck t-shirts in your wardrobe is the key to helping you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirts are dance. Convenient gas for women in everyday wear!<br><br><br>Simple design, convenient form of PPN4502 T-shirt. Why with just 1 basic women's T-shirt that you can The answer lies in their simplicity. The simpler, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design, Gentle on the skin, the sleeve, the form of the shirt is not fussy, very easy to wear with many different body shapes. Minimalism from design, seam to color palette helps women not to hesitate to choose. 95% cotton material is strictly processed, modern process and technology should bring to the dress. dress Comfortable, soft, cool to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. In addition, the product also contains 5% spandex - a type of fiber that helps stretch, elastic effectively suitable to wear to many environments, even when exercising <br><br><br> The presence of clothes Basic round neck t-shirt in your wardrobe is the key to help you have more interesting outfits without needing too many items. Basic round neck cotton women's t-shirt is a handy weapon for women in everyday wear!<br><br><br>Simple design, convenient shape of PPN4502 T-shirt. Why can you combine with just 1 basic women's t-shirt with 10 different sets? The answer lies in their very simplicity. The simpler it is, the easier it is for you to mix & match with different items. PPM4502 Women's T-shirt has a simple round neck design that is gentle on the skin. Fox sleeves, shirt form is not fussy, very easy to wear with many different bodies. More specifically, the color of this round-neck women's t-shirt is also very elegant, neutral, and smooth. The simplicity from design, seam to color palette helps women not to hesitate too much when choosing. 95% cotton material is strictly processed, modern process and technology should give the shirt a comfortable, soft, cool feeling to the touch. Along with that, the Yody round neck cotton women's T-shirt has a very good ability to darken sweat, so the wearer does not feel the feeling of being stuck on the skin when sweating in the summer. Besides, the product also contains 5% spandex - a type of fiber that helps stretch and elastic effectively, suitable for wearing in many environments, even when exercising."
//     },
//     // 18 products
// ];

// function filterItems(arr, item) {
//     // find matched item
//     let duplicate = arr.filter(
//         (product) => 
//         product.slug === item.slug
//         && product.colors === item.colors 
//         && product.size === item.size 
//     );

//     if (duplicate.length > 0) {
//         // let arr is deleted item
//         arr = arr.filter(
//             (product) => product.slug !== item.slug
//             || product.colors !== item.colors
//             || product.size !== item.size
//         );
//         arr = [...arr, {

//         }]
//     }
//     // return deletedItem;
//     return arr[arr.length - 1].quantity;
// }

// console.log(filterItems(products, products[0]));
